service: dawin-log-processor

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs14.x

functions:
  app:
    handler: src/app.handler  
    events:
      - schedule: rate(1 minute)
      # - schedule: cron(0/2 * ? * MON-FRI *)
